name       : razer-drivers
version    : 2.1.1
release    : 64
source     :
    - https://github.com/openrazer/openrazer/releases/download/v2.1.1/openrazer-2.1.1.tar.xz : 7827c2398b695ea002edbd5c7f92fdd722039886f946b35da537ddff9e998f5e
license    : GPL-2.0
component  :
    - kernel.drivers
    - current : kernel.drivers
    - common : system.utils
summary    :
    - A collection of Linux drivers for the Razer devices
    - common : Common component for razer-drivers kernel modules
    - current : razer-drivers for the linux-current kernel
description: |
    A collection of Linux drivers for the Razer devices, providing kernel drivers, DBus services and Python bindings to interact with the DBus interface
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(fftw3)
    - pkgconfig(SDL2_image)
    - pkgconfig(udev)
    - jq
    - linux-lts
    - linux-lts-headers
    - linux-current
    - linux-current-headers
patterns   :
    - common : /*
    - main : /lib/modules/*.lts
    - current : /lib/modules/*.current
permanent  :
    - /lib/modules
rundeps    :
    - common :
        - numpy
        - python-evdev
        - python-notify2
        - python-setproctitle
        - python-daemonize
        - python3-dbus
        - python3-gobject
        - python3-pyudev
        - xaut
        - xdotool
    - razer-drivers-common
    - current :
        - razer-drivers-common
setup      : |
    sed -i "s|depmod||g" Makefile
    pushd ../
    cp -a "openrazer-${version}" lts-build
    cp -a "openrazer-${version}" current-build
build      : |
    pushd ..
    pushd lts-build
    KVER=%kernel_version_lts%
    %make KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid
    pushd ../current-build
    KVER=%kernel_version_current%
    %make KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid
install    : |
    pushd ..
    pushd lts-build
    KVER=%kernel_version_lts%
    install -d -m 00644 $installdir/lib/modules/$KVER/kernel/drivers/hid
    %make install_i_know_what_i_am_doing KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid DESTDIR=$installdir
    # Razer's build system really flops when things already exist.. Autotools wouldn't hurt.
    rm -rf $installdir/usr
    pushd ../current-build
    KVER=%kernel_version_current%
    install -d -m 00644 $installdir/lib/modules/$KVER/kernel/drivers/hid
    %make install_i_know_what_i_am_doing KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid DESTDIR=$installdir

    # Use example file as default configuration
    install -D -m 00644 $installdir/usr/share/openrazer/razer.conf.example $installdir/usr/share/openrazer/razer.conf
