name       : razer-drivers
version    : 1.1.14
release    : 30
source     :
    - https://github.com/terrycain/razer-drivers/archive/v1.1.14.tar.gz : a8ca390f29ecc5d220df8ef00b2bebb54b0ef4551ba2e0245296bb72eb461f41
license    : GPL-2.0
component  : system.utils
summary    : A collection of Linux drivers for the Razer devices
description: |
    A collection of Linux drivers for the Razer devices, providing kernel drivers, DBus services and Python bindings to interact with the DBus interface
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(fftw3)
    - pkgconfig(SDL2_image)
    - pkgconfig(udev)
    - jq
    - linux-lts
    - linux-lts-headers
permanent  :
    - /lib/modules
rundeps    :
    - numpy
    - python-evdev
    - python-notify2
    - python-setproctitle
    - python3-dbus
    - python3-gobject
    - python3-pyudev
    - xaut
    - xdotool
setup      : |
    sed -i "s|depmod||g" Makefile
build      : |
    KVER=%kernel_version_lts%
    %make KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid
install    : |
    KVER=%kernel_version_lts%
    install -dm644 $installdir/lib/modules/$KVER/kernel/drivers/hid

    # They changed the make install functionality yet again ... this is getting tiring.
    %make install_i_know_what_i_am_doing KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid DESTDIR=$installdir

    # Use example file as default configuration
    # This directory has been renamed like 3 times now and its getting seriously annoying
    install -Dm644 $installdir/usr/share/openrazer/razer.conf.example $installdir/usr/share/openrazer/razer.conf
