name       : razer-drivers
version    : 1.1.14
release    : 33
source     :
    - https://github.com/terrycain/razer-drivers/archive/v1.1.14.tar.gz : a8ca390f29ecc5d220df8ef00b2bebb54b0ef4551ba2e0245296bb72eb461f41
license    : GPL-2.0
component  : system.utils
summary    :
    - A collection of Linux drivers for the Razer devices
    - common: Common component for razer-drivers kernel modules
    - current: razer-drivers for the linux-current kernel
description: |
    A collection of Linux drivers for the Razer devices, providing kernel drivers, DBus services and Python bindings to interact with the DBus interface
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(fftw3)
    - pkgconfig(SDL2_image)
    - pkgconfig(udev)
    - jq
    - linux-lts
    - linux-lts-headers
    - linux-current
    - linux-current-headers
patterns   :
    - common: /*
    - main: /lib/modules/*.lts
    - current: /lib/modules/*.current
permanent  :
    - /lib/modules
rundeps    :
    - common:
        - numpy
        - python-evdev
        - python-notify2
        - python-setproctitle
        - python3-dbus
        - python3-gobject
        - python3-pyudev
        - xaut
        - xdotool
    - linux-lts
    - razer-drivers-comment
    - current:
        - razer-drivers-common
setup      : |
    sed -i "s|depmod||g" Makefile
    pushd ../
    cp -a "razer-drivers-${version}" lts-build
    cp -a "razer-drivers-${version}" current-build
build      : |
    pushd lts-build
    KVER=%kernel_version_lts%
    %make KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid
    pushd ../current-build
    KVER=%kernel_version_current%
    %make KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid
install    : |
    pushd lts-build
    KVER=%kernel_version_lts%
    install -d -m 00644 $installdir/lib/modules/$KVER/kernel/drivers/hid
    %make install_i_know_what_i_am_doing KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid DESTDIR=$installdir
    # Razer's build system really flops when things already exist.. Autotools wouldn't hurt.
    rm -rf $installdir/usr
    pushd ../current-build
    KVER=%kernel_version_current%
    install -d -m 00644 $installdir/lib/modules/$KVER/kernel/drivers/hid
    %make install_i_know_what_i_am_doing KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid DESTDIR=$installdir
    
    # Use example file as default configuration
    install -D -m 00644 $installdir/usr/share/openrazer/razer.conf.example $installdir/usr/share/openrazer/razer.conf
