name       : razer-drivers
version    : 1.1.8
release    : 12
source     :
    - https://github.com/terrycain/razer-drivers/archive/v1.1.8.tar.gz : b79df8ae7c1060c4656d1a70ddb3b2178ed9fd0708dfbc9308b539382891bc6e
license    : GPL-2.0
component  : system.utils
summary    : A collection of Linux drivers for the Razer devices
description: |
    A collection of Linux drivers for the Razer devices, providing kernel drivers, DBus services and Python bindings to interact with the DBus interface
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(fftw3)
    - pkgconfig(SDL2_image)
    - pkgconfig(udev)
    - jq
    - linux-lts
    - linux-lts-headers
permanent   :
    - /lib/modules
rundeps    :
    - numpy
    - python-evdev
    - python-notify2
    - python-setproctitle
    - python3-dbus
    - python3-gobject
    - python3-pyudev
    - xaut
    - xdotool
setup      : |
    sed -i "s|depmod||g" Makefile
build      : |
    KVER=4.9.21-13.lts
    %make KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid
install    : |
    KVER=4.9.21-13.lts
    install -dm644 $installdir/lib/modules/$KVER/kernel/drivers/hid
    %make_install KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid

    # Use example file as default configuration
    install -Dm644 $installdir/usr/share/razer-service/razer.conf.example $installdir/usr/share/razer-service/razer.conf
