name       : razer-drivers
version    : 1.1.13
release    : 28
source     :
    - https://github.com/terrycain/razer-drivers/archive/v1.1.13.tar.gz : 33938e72e8815db90f08001ce3e34fa6cc7e78979f57a914ab5f152c8c90a42e
license    : GPL-2.0
component  : system.utils
summary    : A collection of Linux drivers for the Razer devices
description: |
    A collection of Linux drivers for the Razer devices, providing kernel drivers, DBus services and Python bindings to interact with the DBus interface
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(fftw3)
    - pkgconfig(SDL2_image)
    - pkgconfig(udev)
    - jq
    - linux-lts
    - linux-lts-headers
permanent  :
    - /lib/modules
rundeps    :
    - numpy
    - python-evdev
    - python-notify2
    - python-setproctitle
    - python3-dbus
    - python3-gobject
    - python3-pyudev
    - xaut
    - xdotool
setup      : |
    sed -i "s|depmod||g" Makefile
build      : |
    KVER=%kernel_version_lts%
    %make KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid
install    : |
    KVER=%kernel_version_lts%
    install -dm644 $installdir/lib/modules/$KVER/kernel/drivers/hid
    %make_install KERNELDIR=/lib/modules/$KVER/build MODULEDIR=/lib/modules/$KVER/kernel/drivers/hid

    # Use example file as default configuration
    install -Dm644 $installdir/usr/share/razer-daemon/razer.conf.example $installdir/usr/share/razer-daemon/razer.conf
